### ISSUE TITLE
when using 'local' storage the pvc 'live-agent' template doesn't support setting the storageclass

### ISSUE THREAD

**Issue by spielkind** [Cognigy/cognigy-live-agent-helm-chart#2]
Can't define storageclass for local pvc.

volume-claim-storage.yaml
```
{{- if eq .Values.storage.cloudProvider "none" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: live-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end -}}
```
